version: '3'
services:
  db:
    image: mariadb:10.5
    volumes:
      - libviewdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: libview
      MYSQL_DATABASE: libview
      MYSQL_USER: libview
      MYSQL_PASSWORD: libview
    ports:
      - "10003:3306"
  lib:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rdebug-ide --host 0.0.0.0 --port 1234 -- bin/rails s -p 3000 -b 0.0.0.0"
    volumes:
      - .:/app
    environment:
      - BUNDLE_PATH=/app/vendor/bundle
    ports:
      - "1234:1234"
      - "3000:3000"
      - "26162:26162"
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  libviewdata: